-- KeyStorage MySQL Schema
-- 在 aaPanel phpMyAdmin 或 SSH 執行

CREATE TABLE IF NOT EXISTS `keys` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    encrypted_data TEXT NOT NULL,
    iv VARCHAR(64) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_accessed_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS meta (
    `key` VARCHAR(64) PRIMARY KEY,
    value TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
